### ISSUE TITLE
Not bundled jQuery.js with this gem?

### ISSUE THREAD

**Issue by zw963** [opal/opal-jquery#97]
Following is my test project output:

```sh
2017-07-08 13:27:06] INFO  WEBrick 1.3.1
[2017-07-08 13:27:06] INFO  ruby 2.3.3 (2016-11-21) [x86_64-linux]
[2017-07-08 13:27:06] INFO  WEBrick::HTTPServer#start: pid=24468 port=2000
Sprockets::FileNotFound: couldn't find file 'jquery' with type 'application/javascript'
Checked in these paths: 
  /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/opal
  /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/stdlib
  /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib
  /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-jquery-0.4.2/lib
  /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/opal
  /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/rspec/lib
  /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/rspec-core/lib
  /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/rspec-expectations/lib
  /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/rspec-mocks/lib
  /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/rspec-support/lib
  /home/zw963/Project/opal/conway_gol/app
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/resolve.rb:65:in `resolve!'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/context.rb:88:in `resolve'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:259:in `resolve_with_compat'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/context.rb:142:in `require_asset'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/processor.rb:69:in `block in process_requires'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/processor.rb:67:in `each'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/processor.rb:67:in `process_requires'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/processor.rb:48:in `evaluate'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/tilt-2.0.7/lib/tilt/template.rb:109:in `render'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/environment.rb:30:in `find_asset'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/sprockets-3.7.1/lib/sprockets/base.rb:92:in `[]'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets.rb:60:in `javascript_include_tag'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/server.rb:114:in `javascript_include_tag'
	index.html.erb:9:in `block in singleton class'
	index.html.erb:-6:in `instance_eval'
	index.html.erb:-6:in `singleton class'
	index.html.erb:-8:in `__tilt_22179640'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `evaluate'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/tilt-2.0.7/lib/tilt/template.rb:109:in `render'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/server.rb:102:in `html'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/server.rb:92:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/deflater.rb:34:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/server.rb:79:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/lint.rb:49:in `_call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/lint.rb:37:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/chunked.rb:54:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/content_length.rb:15:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
	/home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
127.0.0.1 - - [08/Jul/2017:13:27:11 +0800] "GET / HTTP/1.1" 500 - 0.3898

```

Should we must copy ``jquery-1.12.4.min.js`` and ``jquery-migrate-1.4.1.min.js`` to one ``PATH``
in previous list to make opal-jquery work?

I think bounded with a special version jQuery maybe a better idea

**Comment by elia** [comment]
This is by design to allow users to pick their own version of jQuery

> I think bounded with a special version jQuery maybe a better idea

We may bundle some version of jquery in the future but for now it's better to allow the user to use any version he prefers. This is of course a trade off between ease of use and the ease of using a specific jquery version.

**Comment by zw963** [comment]
@elia , thanks to reply.

What i think is, if anyone need a special jquery version, I think he could do this
manually himself, otherwise, just offer a default version to just work.

**Comment by elia** [comment]
Yeah, and I agree 100% it could be done, but that would also mean keeping
the bundled jquery version up to date and release new versions of
opal-jquery just for that… maybe that's less of a problem than I foresee,
but it's still an additional burden on the maintainer (me! ^-^)
